export const mockSuggestions: GithubProfile[] = [
  {
    login: "mockZach",
    id: 1,
    node_id: "1234",
    avatar_url: "mockAvatar.jpg",
    gravatar_id: "",
    url: "https://api.github.com/users/mockZach",
    html_url: "https://github.com/mockZach",
    followers_url: "https://api.github.com/users/mockZach/followers",
    following_url: "https://api.github.com/users/mockZach/following",
    gists_url: "https://api.github.com/users/mockZach/gists",
    starred_url: "https://api.github.com/users/mockZach/starred",
    subscriptions_url: "https://api.github.com/users/mockZach/subscriptions",
    organizations_url: "https://api.github.com/users/mockZach/organizations",
    repos_url: "https://api.github.com/users/mockZach/repos",
    events_url: "https://api.github.com/users/mockZach/events",
    received_events_url: "https://api.github.com/users/mockZach/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "fakeUser",
    id: 2,
    node_id: "1234",
    avatar_url: "fakeAvatar.jpg",
    gravatar_id: "",
    url: "https://api.github.com/users/fakeUser",
    html_url: "https://github.com/fakeUser",
    followers_url: "https://api.github.com/users/fakeUser/followers",
    following_url: "https://api.github.com/users/fakeUser/following",
    gists_url: "https://api.github.com/users/fakeUser/gists",
    starred_url: "https://api.github.com/users/fakeUser/starred",
    subscriptions_url: "https://api.github.com/users/fakeUser/subscriptions",
    organizations_url: "https://api.github.com/users/fakeUser/organizations",
    repos_url: "https://api.github.com/users/fakeUser/repos",
    events_url: "https://api.github.com/users/fakeUser/events",
    received_events_url: "https://api.github.com/users/fakeUser/received_events",
    type: "User",
    site_admin: false,
  },
];